wandb_version: 1

dataset:
  desc: null
  value: ARC-Challenge
model:
  desc: null
  value: Llama-3.2-1B-Instruct
base_model:
  desc: null
  value: /home/aneek/models/Llama-3.2-1B-Instruct
lora_weights:
  desc: null
  value: /home/aneek/LLM-Adapters/trained_models/llama-commonsense_170k-1B-lora,/home/aneek/LLM-Adapters/trained_models/llama-math_50k-1B-lora,/home/aneek/LLM-Adapters/trained_models/llama-alpaca_data_cleaned-1B-lora
batch_size:
  desc: null
  value: 16
ensemble_rule:
  desc: null
  value: vote
load_8bit:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.54.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752490191
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.17.4
      6: 4.54.0.dev0
      8:
      - 5
      13: linux-x86_64
