wandb_version: 1

dataset:
  desc: null
  value: social_i_qa
model:
  desc: null
  value: Llama-3.2-3B
adapter:
  desc: null
  value: LoRA
base_model:
  desc: null
  value: /home/models/Llama-3.2-3B-Instruct/
lora_weights:
  desc: null
  value: /home/aneek/LLM-Adapters/trained_models/instruction/llama-3B-combined-lora
batch_size:
  desc: null
  value: 16
load_8bit:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.54.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752233890
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      - 61
      4: 3.10.16
      5: 0.17.4
      6: 4.54.0.dev0
      8:
      - 5
      13: linux-x86_64
