wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.54.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752495299
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.10.16
      5: 0.17.4
      6: 4.54.0.dev0
      8:
      - 5
      13: linux-x86_64
